### ISSUE TITLE
감정일기 > 감정 선택 화면 구현

### ISSUE THREAD

**Issue by dev-Lena** [depromeet/bboxx-iOS#42]
## TODO

- [ ] 최소 1개, 최대 5개 감정 선택 가능
- [ ] 감정 버튼이 선택되면 배경색 검정색으로 변경
- [ ] 1~5개가 선택된 경우 "다 골랐어" 버튼 활성화
- [ ] API에서 감정 버튼 이미지, 텍스트 fetch
- [ ] fetch해온 데이터 Button에 표시
